# fly.toml app configuration file generated for hairgan-tensor on 2023-07-26T22:11:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hairgan-tensor"
primary_region = "nrt"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
