name: Fly Deploy
on:
  pull_request:
    branches: ["main"]
    types:
    - closed


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - uses: superfly/flyctl-actions/setup-flyctl@master
      with:
        version: 0.1.66
    - run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}

